
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: qubitro/action-lambda-python-zip@v1.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:ap-southeast-2:386115804199:function:Mytestfunction'
        lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        lambda_region: 'ap-southeast-2'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
